#!/usr/bin/env ruby
# frozen_string_literal: true

# Exit cleanly from an early interrupt
Signal.trap("INT") { abort }

# Clone the repository if not exist and change into it.
#
# Usage:
#
# $ cloneandcd rails/rails
#

owner, repo = ARGV.first.split("/")

clone_url = "https://github.com/#{owner}/#{repo}.git"
path = File.expand_path(File.join(`pwd`.chomp!, repo))
system("git clone #{clone_url}")
Dir.chdir(path) && system("zsh") if $?.exitstatus != 128
