#!/usr/bin/env ruby

# Exit cleanly from an early interrupt
Signal.trap("INT") { abort }

# brew install guetzli

pattern = ARGV.first

def friendly_size(number)
  "#{number/1000} KB"
end

def to_jpg(input)
  File.basename(input) + ".jpg"
end

Dir[pattern].each do |photo|
  base = File.basename(photo)
  before = File.size(photo)
  puts "Compressing #{base} by guetzli."
  puts "Size before: #{friendly_size(before)}"
  system("guetzli", photo, photo)
  after = File.size(photo)
  puts "Size  after: #{friendly_size(after)}. Saved: #{friendly_size(before-after)}"
end
