#!/usr/bin/env ruby -w

# Exit cleanly from an early interrupt
Signal.trap("INT") { abort }

# Find my last commit in git log
#
# Usage:
#
# $ git-my-last-commit
#

`git log -1 -p --author $(git config user.email)`
