#!/usr/bin/env ruby

# heic2jpg IMG_1234.HEIC
# heic2jpg folder

# Exit cleanly from an early interrupt
Signal.trap("INT") { abort }
require "fileutils"

module HEIC2JPG
  def self.run(file)
    directory = File.dirname(file)
    filename = File.basename(file).upcase
    name = File.basename(filename, ".HEIC")
    convert(
      File.join(directory, "#{name}.HEIC"),
      File.join(directory, "#{name}.JPG"),
    )
  end

  def self.convert(input, output)
    puts "Convert #{input} to #{output}"
    exec(
      "magick",
      "convert",
      input,
      "-gravity",
      "center",
      "-crop",
      "3:2",
      "+repage",
      "-quality",
      "90",
      output,
    )
    FileUtils.rm(input)
    puts "Deleted #{input}"
  end
end

input = ARGV[0]

abort("Enter a single .HEIC file or a folder contains .HEIC files") if input.nil?

if File.directory?(input)
  photos = Dir[File.join(input, "*.HEIC")]
  puts "Converting #{photos.size} photos"
  photos.each do |heic|
    puts "Converting #{heic}"
    HEIC2JPG.run(heic)
  end
else
  HEIC2JPG.run(input)
end
