#!/usr/bin/env ruby -w

# Exit cleanly from an early interrupt
Signal.trap("INT") { abort }

# mkdir-p + create file
#
# Usage:
#
# $ mkdir-pf foo/bar/baz
# $ tree foo
# foo
# └── bar
#     └── baz
#
# 1 directory, 1 file

dir_and_file = ARGV.first

dirs = dir_and_file.split(File::Separator)[0..-2].join('/')

`mkdir -p #{dirs} && touch #{dir_and_file}`
