#!/usr/bin/env ruby

# Exit cleanly from an early interrupt
Signal.trap("INT") { abort }

require "fileutils"

# touch + chmod +x
#
# Usage:
#
# $ touchx my-awesome-executable
#

file_name = ARGV.first

default_content = <<~DEFAULT
#!/usr/bin/env ruby

# Exit cleanly from an early interrupt
Signal.trap("INT") { abort }
DEFAULT

File.write file_name, default_content
FileUtils.chmod "+x", file_name
