#!/usr/bin/env ruby -w

# Exit cleanly from an early interrupt
Signal.trap("INT") { abort }

# touch + chmod +x
#
# Usage:
#
# $ touchx my-awesome-executable
#

file_name = ARGV.first
`touch #{file_name} && chmod +x #{file_name}`
