#!/usr/bin/env ruby

# Exit cleanly from an early interrupt
Signal.trap("INT") { fail }

fail("Please clean your local file changes first.") if `git status --porcelain` != ""

fail("Please run this task against master branch.") if `git rev-parse --abbrev-ref HEAD`.chomp! != "master"

require "English"

NEW_VERSION = "2.2.2"

puts "== Upgrade Ruby to #{NEW_VERSION} =="

# .ruby-version

IO.write(".ruby-version", File.open(".ruby-version") do |file|
    file.read.sub(/^ruby-.*$/, "ruby-#{NEW_VERSION}")
  end
)

# Gemfile

IO.write("Gemfile", File.open("Gemfile") do |file|
    content = file.read

    if content.count('"') > content.count("'")
      content.sub(/^ruby .*$/, %(ruby "#{NEW_VERSION}"))
    else
      content.sub(/^ruby .*$/, %(ruby '#{NEW_VERSION}'))
    end
  end
)

puts "== Pulling Latest Changes =="
system "git pull"

# Bundle
puts "== Installing dependencies =="
system "bundle check || bundle install"

puts "== Run tests =="
system "bundle exec rspec"

if $CHILD_STATUS.success?
  puts "== Checkout to a new branch: feature/upgrade-to-ruby-2-2-2 =="
  system "git checkout -b feature/upgrade-to-ruby-2-2-2"

  puts "== Add & Commit & Push =="
  system "git add . && git commit -m 'Upgrade to Ruby 2.2'"
  system "git push origin feature/upgrade-to-ruby-2-2-2"

  puts "== Issue Pull Request =="
  system "hub pull-request -m 'Upgrade Ruby to 2.2.2'"
else
  fail "tests failed. Please check!"
end
