#!/usr/bin/env ruby

# Exit cleanly from an early interrupt
Signal.trap("INT") { fail }

fail("Please clean your local file changes first.") if `git status --porcelain` != ""

fail("Please run this task against master branch.") if `git rev-parse --abbrev-ref HEAD`.chomp! != "master"

require "English"

# Edit these two constant

NEW_VERSION = "2.2.3"
NEW_VERSION_FOR_BRANCH = "2-2-3"

puts "== Upgrade Ruby to #{NEW_VERSION} =="

system "chruby 2.2.3"

# .ruby-version

if File.exist? ".ruby-version"
  IO.write(".ruby-version", File.open(".ruby-version") do |file|
      file.read.sub(/^ruby-.*$/, "ruby-#{NEW_VERSION}")
    end
  )
end

# Gemfile

IO.write("Gemfile", File.open("Gemfile") do |file|
    content = file.read

    if content.count('"') > content.count("'")
      content.sub(/^ruby .*$/, %(ruby "#{NEW_VERSION}"))
    else
      content.sub(/^ruby .*$/, %(ruby '#{NEW_VERSION}'))
    end
  end
)

puts "== Pulling Latest Changes =="
system "git pull"

# Bundle
puts "== Installing dependencies =="
system "bundle check || bundle install"

puts "== Run tests =="
if File.exist? "spec"
  system "bundle exec rspec"
end

if $CHILD_STATUS.success?
  puts "== Checkout to a new branch: feature/upgrade-to-ruby-#{NEW_VERSION_FOR_BRANCH} =="
  system "git checkout -b feature/upgrade-to-ruby-#{NEW_VERSION_FOR_BRANCH}"

  puts "== Add & Commit & Push =="
  system "git add . && git commit -m 'Upgrade to Ruby #{NEW_VERSION}'"
  system "git push origin feature/upgrade-to-ruby-#{NEW_VERSION_FOR_BRANCH}"

  puts "== Issue Pull Request =="
  system "hub pull-request -m 'Upgrade Ruby to #{NEW_VERSION}'"
else
  fail "tests failed. Please check!"
end
